steps:
# 1. Pobieranie i Konfiguracja Fluttera (najnowsza stabilna wersja)
# Używamy prostego obrazu Ubuntu, aby zainstalować Fluttera ręcznie.
- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Zapewnienie, że git jest zainstalowany
      apt-get update && apt-get install -y git
      # Klonowanie najnowszej STABILNEJ wersji Fluttera
      git clone https://github.com/flutter/flutter.git /usr/local/flutter
      /usr/local/flutter/bin/flutter config --enable-web
      
# 2. Budowanie aplikacji (TERAZ NAPRAWIAMY BŁĄD 'PATH')
- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Używamy komendy 'env' zamiast 'export PATH' do modyfikacji ścieżki
      # Zapewnia to, że parser Cloud Build nie zgłasza błędu.
      # Zmienna PATH jest tymczasowo modyfikowana tylko na potrzeby tego kroku.
      env PATH="$PATH:/usr/local/flutter/bin" flutter pub get
      env PATH="$PATH:/usr/local/flutter/bin" flutter build web --release

# 3. Wdrożenie na Firebase Hosting
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'