steps:
# 1. Kompilacja Flutter Web za pomocą aktualnego obrazu Dockerowego
# Wskazujemy konkretny, nowoczesny obraz Fluttera (z Dartem 3.0+), 
# aby uniknąć błędów niezgodności wersji.
- name: 'cirrusci/flutter:3.22.0' # Używamy aktualnej, stabilnej wersji Fluttera
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Aktywacja obsługi web
      flutter config --enable-web
      # Pobranie zależności
      flutter pub get
      # Kompilacja produkcyjna
      flutter build web --release

# 2. Wdrożenie na Firebase Hosting
- name: 'gcr.io/cloud-builders/firebase'
  # Użycie ${PROJECT_ID} automatycznie wskaże projekt GCP/Firebase
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  # Opcja wymagana, gdy używamy niestandardowego konta usługi (jak twoje konto 'compute')
  # Zapewnia, że logi będą zapisywane w Cloud Logging, a nie w GCS.
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s' # Zwiększony limit czasu, aby kompilacja Fluttera miała czas się zakończyć