steps:
# 1. Instalacja Fluttera i Kompilacja (TEN KROK DZIAŁA!)
- name: 'ubuntu' 
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update -y
      apt-get install -y git curl unzip 
      git clone https://github.com/flutter/flutter.git /usr/local/flutter
      /usr/local/flutter/bin/flutter config --enable-web
      /usr/local/flutter/bin/flutter pub get
      /usr/local/flutter/bin/flutter build web --release

# 2. Wdrożenie na Firebase Hosting za pomocą NPM/Node.js
- name: 'gcr.io/cloud-builders/npm' # Używamy stabilnego buildera NPM (Node.js)
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Instalujemy Firebase CLI globalnie w tym kontenerze
      npm install -g firebase-tools
      
      # Wykonujemy deployment na Firebase Hosting
      firebase deploy --only hosting --project ${PROJECT_ID}

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'