steps:
# 1. Instalacja Fluttera i Kompilacja
# Używamy oficjalnego obrazu Ubuntu, który ma apt-get i pozwala na instalację Gita.
- name: 'ubuntu' 
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Instalacja Gita i klonowanie Fluttera (najnowsza stabilna wersja)
      apt-get update -y
      apt-get install -y git # git jest wymagany do klonowania Fluttera
      
      git clone https://github.com/flutter/flutter.git /usr/local/flutter
      
      # Użycie pełnej, bezwzględnej ścieżki do Fluttera (omijanie błędu PATH)
      /usr/local/flutter/bin/flutter config --enable-web
      /usr/local/flutter/bin/flutter pub get
      /usr/local/flutter/bin/flutter build web --release

# 2. Wdrożenie na Firebase Hosting
# Ten builder odczyta skompilowane pliki z katalogu build/web.
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  # Opcja Logowania wymagana przy użyciu niestandardowego konta usługi
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'