steps:
# 1. Kompilacja Flutter Web za pomocą obrazu 'stable'
# Ten tag powinien zawsze wskazywać na najnowszą, stabilną wersję Fluttera,
# co rozwiązuje problem z manifestem i z niezgodnością wersji Darta.
- name: 'cirrusci/flutter:stable' # Zmieniamy na tag 'stable'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Aktywacja obsługi web
      flutter config --enable-web
      # Pobranie zależności
      flutter pub get
      # Kompilacja produkcyjna
      flutter build web --release

# 2. Wdrożenie na Firebase Hosting
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'