steps:
# 1. Pobieranie i Konfiguracja Fluttera (najnowsza stabilna wersja)
# Używamy prostego obrazu Ubuntu, aby zainstalować Fluttera ręcznie.
- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Zapewnienie, że git jest zainstalowany
      apt-get update && apt-get install -y git
      # Klonowanie najnowszej STABILNEJ wersji Fluttera
      git clone https://github.com/flutter/flutter.git /usr/local/flutter
      /usr/local/flutter/bin/flutter config --enable-web
      
# 2. Budowanie aplikacji (teraz ścieżka do Fluttera jest znana)
- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Dodajemy ścieżkę do Fluttera TYLKO dla tego kroku
      export PATH="$PATH:/usr/local/flutter/bin"
      
      # Przejście do katalogu roboczego (jeśli to konieczne, usuń jeśli nie)
      # cd [nazwa_twojego_katalogu_z_projektem] 
      
      flutter pub get
      flutter build web --release

# 3. Wdrożenie na Firebase Hosting
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'