steps:
# 1. Budowanie Flutter Web z użyciem Twojego szybkiego, wstępnie zbudowanego obrazu
# Ten krok jest teraz natychmiastowy, ponieważ obraz jest już gotowy w GCR.
- name: 'gcr.io/mydog24crm/flutter-builder:latest' 
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Nie musimy nic instalować! Wszystko jest już gotowe.
      flutter config --enable-web
      flutter pub get
      flutter build web --release

# 2. Wdrożenie na Firebase Hosting (używamy Node.js, które działało ostatnim razem)
- name: 'node:20' 
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      npm install -g firebase-tools
      firebase deploy --only hosting --project ${PROJECT_ID}

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'