steps:
# 1. Kontener do instalacji Fluttera i kompilacji
# Używamy prostego obrazu Ubuntu i instalujemy Fluttera.
- name: 'bash'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Instalacja Gita i klonowanie Fluttera
      apt-get update && apt-get install -y git
      git clone https://github.com/flutter/flutter.git /usr/local/flutter
      
      # Użycie /usr/local/flutter/bin/flutter bezpośrednio (bez dodawania do PATH)
      /usr/local/flutter/bin/flutter config --enable-web
      
      # Budowanie. WAŻNE: Wymagane jest, aby katalog główny projektu był katalogiem roboczym.
      # Zawsze używamy pełnej ścieżki do Fluttera:
      /usr/local/flutter/bin/flutter pub get
      /usr/local/flutter/bin/flutter build web --release

# 2. Wdrożenie na Firebase Hosting
# Builder Firebase automatycznie odczytuje pliki z katalogu 'build/web'.
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  # Opcja Logowania dla niestandardowego konta usługi.
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'