steps:
# 1. Instalacja Fluttera i Kompilacja
- name: 'ubuntu' 
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Aktualizacja i instalacja niezbędnych narzędzi: git, curl ORAZ unzip
      apt-get update -y
      apt-get install -y git curl unzip # DODANO UNZIP
      
      # Klonowanie najnowszej STABILNEJ wersji Fluttera
      git clone https://github.com/flutter/flutter.git /usr/local/flutter
      
      # Dalsza część bez zmian, używa pełnej ścieżki
      /usr/local/flutter/bin/flutter config --enable-web
      /usr/local/flutter/bin/flutter pub get
      /usr/local/flutter/bin/flutter build web --release

# 2. Wdrożenie na Firebase Hosting
- name: 'gcr.io/cloud-builders/firebase'
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'