steps:
# 1. Kontener roboczy do instalacji i budowania Fluttera
- name: 'bash'
  # Używamy woluminu, aby zapewnić, że skompilowane pliki (build/web) będą dostępne w następnym kroku.
  volumes:
    - name: 'build-volume'
      path: '/workspace'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      # Zapewnienie, że git jest zainstalowany
      apt-get update && apt-get install -y git
      # Klonowanie najnowszej STABILNEJ wersji Fluttera
      git clone https://github.com/flutter/flutter.git /usr/local/flutter
      
      # Dodajemy Fluttera do ścieżki i używamy go tylko w tym kontenerze!
      export PATH="$PATH:/usr/local/flutter/bin"
      
      flutter config --enable-web
      flutter pub get
      
      # Kompilacja. Pliki build/web zostaną zapisane w /workspace.
      flutter build web --release

# 2. Wdrożenie na Firebase Hosting
- name: 'gcr.io/cloud-builders/firebase'
  # Ten krok odczytuje skompilowane pliki z woluminu build-volume.
  volumes:
    - name: 'build-volume'
      path: '/workspace'
  args: ['deploy', '--only', 'hosting', '--project', '${PROJECT_ID}']

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1600s'

volumes:
  # Definicja woluminu, aby pliki mogły być udostępnione.
  - name: 'build-volume'
    path: '/workspace'